name: GitHub Pages Deploy

on:
  push:
    branches:
      -"master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and Build
        run: nom install && npm run build

      - name: Deploy
        uses: Shaike07/xo-game@
        with:
          branch: gh-pages
          folder: build
